[font]
size = 16

[keyboard]
bindings = [
    # Jump words with option left/right
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[font.normal]
# Powerlevel10k support
family = "MesloLGS NF"