[font]
size = 16

[keyboard]
bindings = [
    # Jump words with option left/right
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left",  mods = "Alt", chars = "\u001BB" },
    { key = "Return", mods = "Shift", chars = "\u001b\r" }
]

[font.normal]
# Powerlevel10k support
family = "MesloLGS NF"

[general]
import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"
